### PR TITLE
Updating FPGA Reference Design CMake Files: CRR, DB, GZIP, and QRD

### PR DESCRIPTION
**Pull request by tyoungsc**
## Description
We created a new CMake template for tutorials/reference designs. This PR is a batch change that uses this new template for the CRR, DB, GZIP, and QRD reference designs. For any design that chooses parameter based on the  board, I also added a block for Agilex.

## External Dependencies
Non

## Type of change
Code cleanup

## How Has This Been Tested?

- [X] Command Line
- [X] regtest

### CODE REVIEW

**Review by mdbtucker — APPROVED** [review]

**Comment by jessicadavies-intel** [comment]
LGTM Thanks!

**Comment by anandhv** [comment]
lgtm, thanks Tanner

**Comment by DmitryDenisenko751** [comment]
Thank you, Tanner. Looks good.

**Comment by tyoungsc** [comment]
Closing case to merge into main master

**Pull request closed without merging**
